app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
from django.conf.urls import url

app_name='app1'
urlpatterns = [
    path('form/',views.form,name='form'),
    path('',views.index,name='index'),
    path('list/',views.List.as_view(),name='list'),
    url(r'^list/(?P<pk>\d+)/$',views.Detail.as_view(),name='detail'),
    path('login/', views.login1,name='login'),
    path('logout/', views.logout1,name='logout'),
]

naterich2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]

app1/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone

class Course(models.Model):
    name=models.CharField(max_length=400)
    def __str__(self):
        return self.name


class Student(models.Model):
    CHOICES = (
        ('Part-Payment', 'Part-Payment'),
        ('full-Payment', 'Full-Payment')
    )
    CHOICES1 = (
        ('Enquiary', 'Enquiary'),
        ('Registered', 'Register')
    )
    PAYMENT_CHOICES=(
        ('Cash', 'Cash'),
        ('Card', 'Card'),
        ('Online', 'Online')
    )
    name=models.CharField(max_length=256)
    email=models.CharField(max_length=256,unique=True)
    mobile = models.CharField(max_length=10,unique=True, validators=[RegexValidator(regex='^[6-9]\d{9}$', message='Length has to be 10', code='Invalid number')])
    course=models.ForeignKey(Course,related_name='student_course',on_delete=models.CASCADE)
    city = models.CharField(max_length=256, blank=True, null=True)
    college = models.CharField(max_length=256, blank=True, null=True)
    student_status=models.CharField(max_length=25,choices=CHOICES1)
    enquiary_date=models.DateField()

    fees=models.CharField(max_length=6,blank=True,null=True,validators=[RegexValidator(regex='^\d{4,5}$', message='Fees should be numeric value', code='Invalid number')])
    mode_of_payment=models.CharField(max_length=20,choices=PAYMENT_CHOICES,blank=True,null=True)
    payment_status=models.CharField(max_length=100,choices=CHOICES,blank=True,null=True)
    remaining_fees=models.CharField(max_length=5,blank=True,null=True)
    fees_date=models.DateField(blank=True,null=True)
    remaining_fees_date = models.DateField(max_length=50, blank=True, null=True)
    address=models.TextField(blank=True,null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-fees_date','-enquiary_date')

app1/forms.py
from django import forms
from app1.models import Student

class StudentForm(forms.ModelForm):
    class Meta():
        model=Student
        fields=('__all__')

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.fields['enquiary_date'].label = "Enquiary Date*(Enquiary form ends here-------------------)"
        self.fields['city'].label = "City/District"
        self.fields['college'].label='College(Refrence)'
        self.fields['name'].label = "Name*"
        self.fields['email'].label = 'Email*'
        self.fields['mobile'].label = "Mobile No.*"
        self.fields['course'].label = 'Course*'
        self.fields['student_status'].label = "Student_status*"

app1/views.py
from django.shortcuts import render
from app1.forms import StudentForm
from app1.models import Student
from django.views.generic import TemplateView,ListView,DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse,reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

@login_required
def form(request):
    form=StudentForm()
    if request.method=="POST":
        form=StudentForm(request.POST)
        if form.is_valid():
            form.save()

        else:
            pass
    else:
        pass

    return render(request,'form.html',{'form':form})




def login1(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password = request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            login(request,user)
            return HttpResponseRedirect(reverse('app1:list'))
        else:
            return HttpResponse("your email or password is incorrect")
    return render(request,'login.html',{})

@login_required
def logout1(request):
    logout(request)
    return HttpResponseRedirect(reverse('app1:index'))












def index(request):
    return  render(request,'index.html',{})


class List(LoginRequiredMixin,ListView):
    model = Student
    template_name = 'list.html'
    paginate_by = 10

class Detail(LoginRequiredMixin,DetailView):
    model = Student
    template_name = 'detail.html'

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>




<style>
body{
    background-color: lightblue;
}
input,body{
    border: 1px solid blue;
}
    .jumbotron{
        border: 5px solid blue;
        border-radius: 10px;
        box-shadow: 0 0 15px black;

    }
body{

            background-color: white;
        }
    img{
        width: 150px;
        height: 25px;
    }
</style>
</head>
<body>
<div class="container">
    <div class="jumbotron">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'app1:index' %}">

      <img src="{% static 'image/nrlogo.jpg' %}">
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app1:form' %}">Enquiary Form<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:list' %}">Student List</a>
      </li>




  <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>





            <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:logout' %}">Logout</a>
      </li>

<li class="nav-item">
        <a class="nav-link " href="#">Welcome :{{ user.username|title}}</a>
      </li>

            {% else %}
            <li class="nav-item">
        <a class="nav-link" href="{% url 'app1:login' %}">Login</a>
      </li>

    </ul>

{% endif %}
  </div>
</nav>





</div>
</div>

</body>
 {% block body_block %}





{% endblock %}
</html>

templates/detail.html
{% load mathfilters %}
        {% block body_block %}
<!DOCTYPE html>


<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Detail</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        h1{

            text-align: center;
        }
        table{
            margin-top:50px;
            width: 100%;


        }
        th{
            border: 2px solid gray;

        }
        .jumbotron{
            border: aqua 10px solid;
            background-color: beige;
            border-color: blue;
        }
        th{
            padding-left: 30px;
        }
        p{
            text-align: center;
        }

        table{
            margin-top: 5px;
        }
        #head{
            margin-top: 5px;
        }
        #x{
            border-style: none;
        }


    </style>
</head>
<body>
<div class="container">
    <div class="jumbotron">
        <h1 id ="head"><em><u>NetRich IT Solution</u> </em></h1>
        <p> MIG-230,2nd Floor,Above IDBI Bank,Adj:RS Brother and J S BABU Silk,</p>
        <p>KPHB Colony,Back side of KPHB Bus Stop, Hyd-072,</p>
        <p><strong>PH: 040-48555314,9948999521,www.netrich.in</strong></p>
        <h1>RECEIPT</h1>
        <div class="t1">
        <table class="newt">
            <thead>
            <th style="border-style: none">Serial No.{{ student.id}}</th>
            <th id="x" style="text-align: right " >GST Number : 36AA0FN6969Q1ZO </th>
            </thead>
        </table>
            </div>


<table>
  <thead >
  <th>Name</th>
  <th>{{ student.name|title }}</th>
  </thead><br>
  <thead>
  <th>Email</th>
  <th>{{ student.email }}</th>
  </thead>
    <thead>
  <th>Course</th>
  <th>{{ student.course|title }}</th>
  </thead>


    <thead>
  <th>Fees</th>
  <th>{{ student.fees|mul:100|div:118|floatformat:'0' }}</th>
  </thead>
    <thead>
  <th>GST</th>
  <th>{{ student.fees|mul:18|div:118|floatformat:'0' }}</th>
  </thead>
     <thead>
  <th>Total Received</th>
  <th>{{ student.fees}}</th>
  </thead>
    <thead>
  <th>Payment Date</th>
  <th>{{ student.fees_date }}</th>
  </thead>
    <thead>
  <th>Payment Status</th>
  <th>{{ student.payment_status|title }}</th>
      <thead>
  <th>Remaining Fess</th>
  <th>{{ student.remaining_fees|mul:100|div:118|floatformat:'0'}}</th>
  </thead>
    <thead>
  <th> Remaining GST</th>
  <th>{{ student.remaining_fees|mul:18|div:118|floatformat:'0'}}</th>
  </thead>
    <thead>
  <th> Total Remaining Amount</th>
  <th>{{ student.remaining_fees }}</th>
  </thead>

    <thead>
  <th>Remaining Fees Date (Expected/Paid)</th>
  <th>{{ student.remaining_fees_date }}</th>
  </thead>
</table>
</table><br><br>
<h5 style="text-align: right">Authorised Signature with Seal</h5><br>
        <h2>Terms and Conditions :</h2>
<ol>
    <li>Organization reserves the right to expand any student during the training period.</li>
    <li>Fees once paid will not be refunded or adjusted against other course/batches/student under any circumstances whatsoever.</li>
    <li>Student should always carry their id card with them and shall produce the same as and when requested.</li>
    <li>Once the batch is allotted it will be permanent and no shifting will be entertained.</li>
    <li>in case,a student fails to attend the given batch the amount given will be forfeited against his/her name.</li>
    <li>Payment of cheques are subject to realization.</li>
    <li>Vehicle are kept at owner risk.</li>
    <li>Any discrepancies are subjected to Hyderabad Jurisdiction.</li>
</ol>
</div>
</div>
</body>
</html>
{% endblock %}

templates/form.html
 {% extends 'base.html' %}
        {% block body_block %}
<!DOCTYPE html>
    <html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script>
                $(function() {
                        $( "#id_enquiary_date" ).datepicker({
                                dateFormat: "yy-mm-dd",
                                defaultDate: "+1w",
                                changeMonth: true,
                                numberOfMonths: 1,
                                onClose: function( selectedDate ) {
                                        $( "#id_birth_date" ).datepicker( "option", "minDate", selectedDate );
                                }
                        });
                });
                $(function() {
                        $( "#id_fees_date" ).datepicker({
                                dateFormat: "yy-mm-dd",
                                defaultDate: "+1w",
                                changeMonth: true,
                                numberOfMonths: 1,
                                onClose: function( selectedDate ) {
                                        $( "#id_birth_date" ).datepicker( "option", "minDate", selectedDate );
                                }
                        });
                });
                 $(function() {
                        $( "#id_remaining_fees_date" ).datepicker({
                                dateFormat: "yy-mm-dd",
                                defaultDate: "+1w",
                                changeMonth: true,
                                numberOfMonths: 1,
                                onClose: function( selectedDate ) {
                                        $( "#id_birth_date" ).datepicker( "option", "minDate", selectedDate );
                                }
                        });
                });
        </script>
    <style>
        input,textarea{
            width: 100%;
        }

        .jumbotron{
            border: 3px solid blue;
        }
        h1{
            text-align: center;
            color: blue;
        }
        #id_course,#id_payment_status,#id_student_status,#id_mode_of_payment
        {
            width: 100%;
        }
         form{
            width: 40%;
        }

    </style>
</head>
<body>

<div class="container">
    <div class="jumbotron">
        <h1><em>Student Enquiary and Payment Form</em></h1><br><br>
<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input class="btn btn-outline-primary" type="submit" value="SUBMIT">
</form>
</div>
</div>
</body>
</html>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
        {% block body_block %}
<!DOCTYPE html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <style>
        h1{
            color: blue;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="jumbotron">
<h1><em>Welcome to NetRich IT Solution!! !!</em></h1>

    </div>
    </div>
</body>
</html>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% block body_block %}
<!DOCTYPE html>

<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>

<div class="container">
<div class="jumbotron">
  <h2>Student Details</h2>
  <p>List of Students in the Table</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Mobile</th>
          <th>Course</th>
        <th>City</th>
        <th>Mode of payment</th>
           <th>Fees</th>
        <th>Fees date</th>
          <th>IdCard/PaymentReceipt</th>

      </tr>
    </thead>
      {% for x in student_list %}
    <tbody>
      <td>{{ x.name }}</td>
        <td>{{ x.email }}</td>
        <td>{{ x.mobile }}</td>
    <td>{{ x.course }}</td>
        <td>{{ x.city }}</td>
        <td>{{ x.mode_of_payment}}</td>
       <td>{{ x.fees }}</td>
        <td>{{ x.fees_date }}</td>
        <td><a href="{{ x.id }}">View</a> </td>
    </tbody>
      {% endfor %}
  </table>
</div>
{% include "pagination.html" with page=page_obj %}
</div>

</body>
</html>
{% endblock %}

templates/login.html
  {% extends 'base.html' %}
        {% block body_block %}
            <style>
input,button{
    width: 100%;
}
 form{
                width: 40%;
            }
            .btn{
                width: 60%;
                height: 50px;
            }

            </style>
<div class="container">
    <div class="jumbotron">
<form method="POST">
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter username">

  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" class="form-control"  placeholder="Password">
  </div>
  <button type="submit" class="btn btn-primary">Login</button>
    {% csrf_token %}
</form>













</div>
    </div>

  {% endblock %}

templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>